### ISSUE TITLE
Release 1.0.2 package is missing the code

### ISSUE THREAD

**Issue by ab-pm** [Wideplink/eslint-plugin-named-import-spacing#59]
In the distributed package of v1.0.2, [the `dist` folder is missing](https://www.npmjs.com/package/eslint-plugin-named-import-spacing/v/1.0.2?activeTab=explore), there's only `.vscode` (which probably shouldn't be shipped).
In v1.0.1, [it was still there](https://www.npmjs.com/package/eslint-plugin-named-import-spacing/v/1.0.1?activeTab=explore).

**Comment by mtripg6666tdr** [comment]
oops :joy:
I'm sorry again. I'm gonna republish it soon

**Comment by mtripg6666tdr** [comment]
I fixed it now!
I'm sorry for inconvenience, and thank you so much for the issue!

**Comment by eve0415** [comment]
LMAO
